### ISSUE TITLE
[Trang Chu] (Cập nhật thông tin giáo xứ) Không cập nhật thông tin giáo xứ, hiển thị thông báo không hợp lý

### ISSUE THREAD

**Issue by thoamtk** [khoannd/qlgp#9]
Tại tab Trang chủ/Thông tin giáo xứ:
Bước 1: Nhấp vào nút Cập nhật thông tin
Bước 2: Chỉnh sửa thông tin bất kỳ, hoặc không chỉnh sửa
Bước 3: Nhấp vào nút "Cập Nhật" 
**Issue1:** Sau khi nhấp vào nút Cập Nhật, Email là không bắt buộc nhưng nếu không nhập gì sẽ hiện thông báo "Email không đúng định dạng (Ví dụ: pms@gmail.com)"
![image](https://github.com/khoannd/qlgp/assets/139546008/eed4da09-98c3-4b60-a1bd-f49443c92cc0)
**Issue2:** Nút Cập Nhật không hoạt động, không thể cập nhật thông tin đã nhập.

**Comment by anhthoai1133** [comment]
Tôi k thể tìm thấy mục nào liên quan đến Thông tin giáo xứ, hoặc mục nào liên quan đến cập nhật giáo xứ.
